sudo: false
cache: bundler
language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.2.0
- 2.1.8
- 2.1.0
- 2.0.0-p648
- 2.0.0
- 1.9.3
- 1.8.7
- ruby
- ruby-head
- jruby
- jruby-19mode
- jruby-head
- rbx-2
- rbx-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: rbx-head
notifications:
  email:
    recipients:
      secure: uNvjRODryNBidq+HVoEkiGNXWWMqsDYPzD8EdU/6ndiJVDtM5UgjcZTP9smVoCkFSX7v/N21/yKNrt6n4eGQuCo1SxM2cEXMKLsBlfGPV5lad+6/V3utl4vDgViyuZOR+RaBfIn1zNv9swzy7TUCwFOcALa+QVPZC8IGW2esUDesnZWjRAq32uM1uK9xLevYvrPR031qn1EVBG4r6VmUnKNAy4GbzIFmtyZQn6BckPP5UgVwIkVePlr6Rkqdk09Ax4Mx3fYF/G+ctVdrkMVvXYsoh8sQUYrofeYz0LwrhsjVTTdV2ZWsJ7HxgEEkE+AU2YzGnDqNUR2muw6/RUjJ21lYlvHXXfv7xevIehr9ZiwToJTbm0LyTgZtuxd8XjYV8PSpTvsxMCkgOC1qiNV2vs0VAMRuO8iO9ct8982cC7VjCCcQqo1GWgrUaYbeaFuLO1Sgj8HTpTgaAnU5/7002bvv53x31VY1eb8eAHXLriJTAitC5qyw2gQYQ5IlTSWpcNue27ROHLfxmLJ2lGjGFbDezeDqW/2g7Eumr0ONyTEuPoGuNwh0XZjQcFC/jXIiw+czE3/OJ9DRIEvmM+AvAv6fSAs4BCzTkNXnTaAMMa9Iz049SFLKQkdoB/DPew7d7IZYKaAtYA5owMjUG+KG5u4b3NRSGQmT/+mzZwB8xIw=
    on_success: always
    on_failure: always
  webhooks:
  - https://zapier.com/hooks/catch/2y1h4a/
  slack:
    secure: CQ+rNTyD98rgLqmcvtZlB3lehGMZ0hndLd2Y75pKQopMFAvfAECUmoueTP5k2niIhQFfPvZnjoaId1sueIQwlT9XDoOzYC0sNCKTQyzPS1LFv3+mjf7DOsSNwf60gQUvwo1OpcxTqVSc6OxaiSMQOd1AZ9HN6EcuDIk/KHbQ7ugL9Q1I1397/k3QEcW+xPfDCE0r5nVYmAYGt8UisKSVEiReSu8mppbCrg2I0Lr7iX/o+nrGDDgyFo0H8sszb3aUXprkpaNLsU7EhxZtp6wZbk6s/6Dr8MZ1P3tb7ItQija/V44OH2B43xlZdo463P+AlOnAaJP9xLCZlA70GOxnEcZPI459fCzXwPUES1XKoaDt//NgjcLx9GlodfBz79Sz0S9BAN0DHyZ/Ev+juy3Q1wJrls53T+pUXCTYLVG+lhysCd/+4SKv/9NDuZrwnNPTNPBBjsFB1Ysbx62+VzzhmblpQlH+3tR0n5CaCVTFeZvtjJgemt0yXGcU2b9ut7p7eBc83L/b6lVsEGySkHK/XQYOEaz6Ns06IFi3mDw/KXKJVAie36lQus+bpitaFH2vbmtWbUlshvvizG31PlBtHjjwcZQfLHBd+waAeWKT1KNUdBS9zfBcwcrjpRGwTCtZmSFkqv3z4s9vSPWq1PYfKX/RqghdPHSTIOgdjQmjpYc=
