sudo: false
cache: bundler
language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.2.0
- 2.1.8
- 2.1.0
- 2.0.0-p648
- 2.0.0
- 1.9.3
- 1.8.7
- ruby
- ruby-head
- jruby
- jruby-19mode
- jruby-head
- rbx-2
- rbx-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: rbx-head
notifications:
  email:
    recipients:
    - johncwang@gmail.com
    on_success: always
    on_failure: always
  webhooks:
  - https://zapier.com/hooks/catch/2y1h4a/
  slack:
    secure: CQ+rNTyD98rgLqmcvtZlB3lehGMZ0hndLd2Y75pKQopMFAvfAECUmoueTP5k2niIhQFfPvZnjoaId1sueIQwlT9XDoOzYC0sNCKTQyzPS1LFv3+mjf7DOsSNwf60gQUvwo1OpcxTqVSc6OxaiSMQOd1AZ9HN6EcuDIk/KHbQ7ugL9Q1I1397/k3QEcW+xPfDCE0r5nVYmAYGt8UisKSVEiReSu8mppbCrg2I0Lr7iX/o+nrGDDgyFo0H8sszb3aUXprkpaNLsU7EhxZtp6wZbk6s/6Dr8MZ1P3tb7ItQija/V44OH2B43xlZdo463P+AlOnAaJP9xLCZlA70GOxnEcZPI459fCzXwPUES1XKoaDt//NgjcLx9GlodfBz79Sz0S9BAN0DHyZ/Ev+juy3Q1wJrls53T+pUXCTYLVG+lhysCd/+4SKv/9NDuZrwnNPTNPBBjsFB1Ysbx62+VzzhmblpQlH+3tR0n5CaCVTFeZvtjJgemt0yXGcU2b9ut7p7eBc83L/b6lVsEGySkHK/XQYOEaz6Ns06IFi3mDw/KXKJVAie36lQus+bpitaFH2vbmtWbUlshvvizG31PlBtHjjwcZQfLHBd+waAeWKT1KNUdBS9zfBcwcrjpRGwTCtZmSFkqv3z4s9vSPWq1PYfKX/RqghdPHSTIOgdjQmjpYc=
